main: ga.strikepractice.striketab.StrikeTab
version: 0.3.11
name: StrikeTab
author: Toppe
website: https://github.com/toppev/strike-tab
description: Tablist addon for StrikePractice
depend: [PlaceholderAPI, ProtocolLib]
softdepend: [StrikePractice, Citizens, ViaVersion, ViaRewind, Tabbed]
commands:
  striketab:
    aliases: [spractab]

permissions:
  striketab.admin:
    description: Admin permissions to /striketab commands, update notifications etc.
    default: false
