main: ga.strikepractice.striketab.StrikeTab
version: 0.2.0
name: StrikeTab
author: Toppe5
description: Tablist addon for StrikePractice
depend: [ StrikePractice, PlaceholderAPI, ProtocolLib ]
softdepend: [ Citizens, ViaVersion, ViaRewind ]
commands:
  striketab:
    aliases: [ spractab ]

permissions:
  striketab.admin:
    description: Admin permissions to /striketab commands, update notifications etc.
    default: false