main: ga.strikepractice.striketab.StrikeTab
version: 0.1.5
name: StrikeTab
author: Toppe5
depend: [StrikePractice, PlaceholderAPI, ProtocolLib]
softdepend: [Citizens]
commands:
  striketab:
    aliases: [spractab]

permissions:
  striketab.admin:
    description: Admin permissions to /striketab commands, update notifications etc.
    defaultf: false