name: Run tests
# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: "./gradlew build"
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --scan --no-build-cache build
        env:
          CI: true
      - name: Check no git diff
        run: git diff --exit-code